In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.19.0'

In [3]:
scalar = tf.constant(1)
scalar.dtype

tf.int32

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([3,3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
vector2d = tf.constant([[1,2],[3,4]])
vector2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [8]:
vector2d.ndim

2

In [9]:
vector2d = tf.constant([[1,2],[3,4]] , dtype = tf.int16)
vector2d

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 4]], dtype=int16)>

In [10]:
vector3d = tf.constant([[[1,2],[3,4]],
                       [[4,5],[6,7]]], dtype = tf.int16)
vector3d

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]], dtype=int16)>

In [11]:
vector3d.ndim

3

In [12]:
scalar1 = tf.Variable(10)
scalar1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [13]:
scalar1.assign(3)
scalar1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [14]:
vector_2 = tf.Variable([1,2,3,4])
vector_2

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [15]:
vector_2[0].assign(0)
vector_2

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([0, 2, 3, 4], dtype=int32)>

In [16]:
random_1 = tf.random.Generator.from_seed(42)
print(random_1)

In [17]:
random_1 = random_1.normal([3,3])
random_1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193765, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535806 ]], dtype=float32)>

In [18]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal([3,3])
random_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193765, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535806 ]], dtype=float32)>

In [19]:
random_1==random_2

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [20]:
vector = tf.random.Generator.from_seed(42)
vector

In [21]:
vector = vector.uniform(
    shape=(15, 2),
    minval=0,
    maxval=10,
    dtype=tf.int32 )
vector

<tf.Tensor: shape=(15, 2), dtype=int32, numpy=
array([[3, 7],
       [6, 8],
       [6, 1],
       [1, 7],
       [2, 7],
       [1, 6],
       [0, 3],
       [5, 2],
       [8, 3],
       [6, 7],
       [3, 9],
       [8, 9],
       [4, 9],
       [6, 7],
       [5, 4]], dtype=int32)>

In [22]:
vector_shuffled = tf.random.shuffle(vector)

In [23]:
vector_shuffled

<tf.Tensor: shape=(15, 2), dtype=int32, numpy=
array([[1, 7],
       [8, 9],
       [6, 7],
       [5, 4],
       [1, 6],
       [3, 9],
       [2, 7],
       [8, 3],
       [4, 9],
       [6, 7],
       [0, 3],
       [6, 8],
       [6, 1],
       [3, 7],
       [5, 2]], dtype=int32)>

In [24]:
print(f'vector before shuffle is : \n{vector},\n after shuffle is {vector_shuffled}')

vector before shuffle is : 
[[3 7]
 [6 8]
 [6 1]
 [1 7]
 [2 7]
 [1 6]
 [0 3]
 [5 2]
 [8 3]
 [6 7]
 [3 9]
 [8 9]
 [4 9]
 [6 7]
 [5 4]],
 after shuffle is [[1 7]
 [8 9]
 [6 7]
 [5 4]
 [1 6]
 [3 9]
 [2 7]
 [8 3]
 [4 9]
 [6 7]
 [0 3]
 [6 8]
 [6 1]
 [3 7]
 [5 2]]


In [25]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [26]:
tf.zeros(shape = (3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [27]:
import numpy as np
arr = np.arange(1,25,dtype = np.int32)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [28]:
tensor = tf.constant(arr,shape = [2,4,3])
tensor

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [29]:
tensor+100

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[101, 102, 103],
        [104, 105, 106],
        [107, 108, 109],
        [110, 111, 112]],

       [[113, 114, 115],
        [116, 117, 118],
        [119, 120, 121],
        [122, 123, 124]]], dtype=int32)>

In [30]:
tensor-100

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[-99, -98, -97],
        [-96, -95, -94],
        [-93, -92, -91],
        [-90, -89, -88]],

       [[-87, -86, -85],
        [-84, -83, -82],
        [-81, -80, -79],
        [-78, -77, -76]]], dtype=int32)>

In [31]:
tensor*10

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]],

       [[130, 140, 150],
        [160, 170, 180],
        [190, 200, 210],
        [220, 230, 240]]], dtype=int32)>

In [32]:
tensor

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [33]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]],

       [[130, 140, 150],
        [160, 170, 180],
        [190, 200, 210],
        [220, 230, 240]]], dtype=int32)>

In [34]:
tensor / 10

<tf.Tensor: shape=(2, 4, 3), dtype=float64, numpy=
array([[[0.1, 0.2, 0.3],
        [0.4, 0.5, 0.6],
        [0.7, 0.8, 0.9],
        [1. , 1.1, 1.2]],

       [[1.3, 1.4, 1.5],
        [1.6, 1.7, 1.8],
        [1.9, 2. , 2.1],
        [2.2, 2.3, 2.4]]])>

In [35]:
tensor = tensor ** 2

In [36]:
tensor

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81],
        [100, 121, 144]],

       [[169, 196, 225],
        [256, 289, 324],
        [361, 400, 441],
        [484, 529, 576]]], dtype=int32)>

In [37]:
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[96, 37, 93, 92, 33, 89, 41, 58, 85, 90,  8, 94, 79, 60, 74,
           60, 76, 11, 25, 17, 82, 17, 86, 96, 16, 59, 67, 76, 40, 15,
           57, 23, 84,  4, 35, 89, 91, 94, 78, 92, 50, 43,  6, 63, 14,
           62, 42,  7, 94, 21]]]]])>

In [38]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([96, 37, 93, 92, 33, 89, 41, 58, 85, 90,  8, 94, 79, 60, 74, 60, 76,
       11, 25, 17, 82, 17, 86, 96, 16, 59, 67, 76, 40, 15, 57, 23, 84,  4,
       35, 89, 91, 94, 78, 92, 50, 43,  6, 63, 14, 62, 42,  7, 94, 21])>

In [39]:
G_squeezed.shape, G_squeezed.ndim


(TensorShape([50]), 1)

In [40]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [41]:
!nvidia-smi

Wed Feb 18 12:05:53 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   56C    P0             29W /   70W |     109MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----